#' Plot UMAP comparisons across all batch correction methods
#'
#' @description
#' `plot_batch_comparison()` generates a grid of UMAP plots — one per method —
#' coloured by batch and optionally by cell type, for visual comparison of
#' integration quality.
#'
#' @param results An `OmicsBatchR` list from [run_batch_correction()].
#' @param color_by Character vector. Metadata columns to colour by.
#'   Default: `"batch"`.
#' @param ncol Integer. Number of columns in the plot grid. Default: `3`.
#' @param point_size Numeric. Point size. Default: `0.5`.
#' @param alpha Numeric. Point transparency (0-1). Default: `0.6`.
#' @param title Character. Overall plot title.
#' @param save_path Character or NULL. If provided, saves the plot as a PDF.
#' @param width Numeric. PDF width in inches. Default: `16`.
#' @param height Numeric. PDF height in inches. Default: `10`.
#'
#' @return A `patchwork` ggplot object (invisibly if saved).
#'
#' @examples
#' \dontrun{
#' results <- run_batch_correction(obj, batch_key = "batch")
#' plot_batch_comparison(results, color_by = c("batch", "cell_type"))
#' }
#'
#' @export
plot_batch_comparison <- function(results,
                                  color_by   = "batch",
                                  ncol       = 3,
                                  point_size = 0.5,
                                  alpha      = 0.6,
                                  title      = "Batch correction comparison \u2014 OmicsBatchR",
                                  save_path  = NULL,
                                  width      = 16,
                                  height     = 10) {

  if (!inherits(results, "OmicsBatchR")) {
    stop("'results' must be an OmicsBatchR object.")
  }

  umap_names <- c(
    harmony    = "umap_harmony",
    seurat_cca = "umap_seurat_cca",
    combat     = "umap_combat",
    fastmnn    = "umap_fastmnn",
    scanorama  = "umap_scanorama",
    bbknn      = "umap_bbknn",
    scvi       = "umap_scvi"
  )

  all_plots <- list()

  for (color_col in color_by) {
    for (method in names(results)) {
      obj      <- results[[method]]
      umap_key <- umap_names[method]

      if (is.na(umap_key) || !umap_key %in% names(obj@reductions)) next
      if (!color_col %in% colnames(obj@meta.data)) next

      coords <- as.data.frame(Seurat::Embeddings(obj, reduction = umap_key))
      colnames(coords) <- c("UMAP_1", "UMAP_2")
      coords[[color_col]] <- obj@meta.data[[color_col]]

      n_cats <- length(unique(coords[[color_col]]))

      p <- ggplot2::ggplot(coords,
                           ggplot2::aes(x = .data[["UMAP_1"]],
                                        y = .data[["UMAP_2"]],
                                        color = .data[[color_col]])) +
        ggplot2::geom_point(size = point_size, alpha = alpha) +
        ggplot2::labs(
          title    = toupper(method),
          subtitle = sprintf("coloured by: %s", color_col),
          color    = color_col
        ) +
        ggplot2::theme_bw(base_size = 11) +
        ggplot2::theme(
          plot.title   = ggplot2::element_text(face = "bold", size = 12),
          legend.position = "right",
          axis.text    = ggplot2::element_blank(),
          axis.ticks   = ggplot2::element_blank(),
          panel.grid   = ggplot2::element_blank()
        ) +
        ggplot2::guides(
          color = ggplot2::guide_legend(override.aes = list(size = 3, alpha = 1))
        )

      if (n_cats <= 12) {
        p <- p + ggplot2::scale_color_brewer(palette = "Paired")
      } else {
        p <- p + ggplot2::scale_color_viridis_d()
      }

      all_plots[[paste(method, color_col, sep = "_")]] <- p
    }
  }

  if (length(all_plots) == 0) {
    stop("No plots could be generated. Check reductions and metadata columns.")
  }

  combined <- patchwork::wrap_plots(all_plots, ncol = ncol) +
    patchwork::plot_annotation(
      title   = title,
      caption = "Generated by OmicsBatchR",
      theme   = ggplot2::theme(
        plot.title   = ggplot2::element_text(size = 16, face = "bold", hjust = 0.5),
        plot.caption = ggplot2::element_text(size = 9, color = "grey50")
      )
    )

  if (!is.null(save_path)) {
    ggplot2::ggsave(save_path, combined, width = width, height = height, device = "pdf")
    message(sprintf("Plot saved to: %s", save_path))
  }

  return(combined)
}


#' Plot benchmark scores as a bar chart
#'
#' @description
#' `plot_benchmark_scores()` visualises the LISI, kBET, and overall scores
#' from [benchmark_methods()] as a faceted bar chart.
#'
#' @param benchmark_df A data frame from [benchmark_methods()].
#' @param save_path Character or NULL. Path to save PDF. Default: `NULL`.
#' @param width Numeric. PDF width. Default: `10`.
#' @param height Numeric. PDF height. Default: `6`.
#'
#' @return A ggplot object.
#'
#' @examples
#' \dontrun{
#' scores <- benchmark_methods(results, batch_key = "batch")
#' plot_benchmark_scores(scores)
#' }
#'
#' @export
plot_benchmark_scores <- function(benchmark_df,
                                  save_path = NULL,
                                  width     = 10,
                                  height    = 6) {

  score_cols <- "iLISI"
  if ("cLISI" %in% colnames(benchmark_df) && !all(is.na(benchmark_df$cLISI))) {
    score_cols <- c(score_cols, "cLISI")
  }
  score_cols <- c(score_cols, "kBET_acceptance", "overall_score")

  long_df <- tidyr::pivot_longer(
    benchmark_df[, c("method", score_cols), drop = FALSE],
    cols      = -"method",
    names_to  = "metric",
    values_to = "score"
  )

  metric_labels <- c(
    iLISI           = "iLISI (batch mixing)\nhigher = better",
    cLISI           = "cLISI (cell-type preservation)\nlower = better",
    kBET_acceptance = "kBET acceptance rate\nhigher = better",
    overall_score   = "Overall score\nhigher = better"
  )

  long_df$metric_label <- metric_labels[long_df$metric]
  long_df$metric_label <- factor(long_df$metric_label,
                                 levels = metric_labels[score_cols])

  method_order   <- benchmark_df$method[order(benchmark_df$overall_score,
                                               decreasing = TRUE)]
  long_df$method <- factor(long_df$method, levels = method_order)

  p <- ggplot2::ggplot(long_df,
                       ggplot2::aes(x = .data[["method"]],
                                    y = .data[["score"]],
                                    fill = .data[["method"]])) +
    ggplot2::geom_col(width = 0.7, alpha = 0.85) +
    ggplot2::geom_text(
      ggplot2::aes(label = round(.data[["score"]], 2)),
      vjust = -0.4, size = 3.2, color = "grey30"
    ) +
    ggplot2::facet_wrap(~ metric_label, scales = "free_y", ncol = 2) +
    ggplot2::scale_fill_brewer(palette = "Set2") +
    ggplot2::labs(
      title    = "Batch correction benchmark \u2014 OmicsBatchR",
      subtitle = "Comparison of integration quality metrics across methods",
      x        = NULL,
      y        = "Score",
      fill     = "Method",
      caption  = "Generated by OmicsBatchR"
    ) +
    ggplot2::theme_bw(base_size = 12) +
    ggplot2::theme(
      axis.text.x  = ggplot2::element_text(angle = 35, hjust = 1),
      strip.text   = ggplot2::element_text(face = "bold", size = 10),
      plot.title   = ggplot2::element_text(face = "bold", size = 14),
      legend.position = "none"
    )

  if (!is.null(save_path)) {
    ggplot2::ggsave(save_path, p, width = width, height = height, device = "pdf")
    message(sprintf("Plot saved to: %s", save_path))
  }

  return(p)
}
